### PR TITLE
README: add Tridactyl install; upd Browser-side text

### PR DESCRIPTION
**Pull request by Anton-Latukha**
Changes can be tested [here](https://github.com/Anton-Latukha/org-protocol-capture-html/blob/add-doc-trodactyl/README.org).

### CODE REVIEW

**Comment by alphapapa** [comment]
Hi,

Thanks for the PR.  I will try to get to it soon.

**Comment by Anton-Latukha** [comment]
Please. How the things are going?

My setup all this time works very nicely.

**Comment by alphapapa** [comment]
Sorry for the delay.  Some feedback:

1.  Why did you change `Bookmarklet` to `Browser-side script`?
2.  The Tridactyl information looks helpful.  Can you please clarify this part of the code?  I don't understand the comments, because I can't tell if they're descriptive or instructive.  Instructions should be presented outside of the source code.
```
// See if key is binded:
:bind <key>
// Observe is it empty `:# <key> = `. If it not - choose other key, or do `:unbind <key>`.
```

**Comment by Anton-Latukha** [comment]
@alphapapa 

About `1`, why browser-side scripts:
1) People forgot what bookmarklets are. I use to use them while I was a kid, but I needed to refresh, learn again my knowledge on what bookmarklet is. So browser-side script is a right away understandable term for all users.
2) Because scripts in Pentadactyl (which already documented there in docs) and in Tridactyl are not bookmarklets. They are separate scripts, and they have nothing to do to the internal bookmark system of the browser.

About `2`, a block of JS code instructions for Tridactyl: command form `:bind <key>` without additional argument - outputs what is currently binded to the key, so people only knowingly would bind function over something other. And you are right, it is instructive, I added the update.

**Comment by alphapapa** [comment]
It may be a matter of opinion to some extent, but I think "bookmarklet" is still a correct term, because AFAIK it's executed in the context of the page as if it were pasted into the address bar or accessed as a bookmark.  The term "browser-side script" seems less useful to me, because all such JavaScript scripts are browser-side (since there is no, e.g. Node.js server involved), and without using an extension like GreaseMonkey or the developer console, there is no way to run arbitrary scripts on-demand.

Having said that, if it's really a problem for users to call it a bookmarklet, we could mention `(browser-side script)` somewhere.  But I'd generally prefer to keep the documentation minimal, because users can easily look up the term "bookmarklet" if they aren't familiar with it.

In the same way, I think we should omit instructions about checking for existing binds, because that's not necessary to configure this tool.  Users should refer to Tridactyl documentation on that if necessary.

**Comment by Anton-Latukha** [comment]
BTW, I've made an extensive research back in the day on this. But was so fired-up than decided to not post it.

From the top of my head.

There is a loophole in browsers. Creator of JavaScript in Netscape back in a day in specs established a `javascript://` type of URL to execute scripts inside the browser for modification of the browser (server side script execution).

Then he was astonished that people started using it for all kinds of things and that its integration with bookmarks worked, and that was not the expected outcome for him, not outcome and use he thought initially.

I found a historical source of the origin of "Bookmarklets" term.

"Bookmarklets" is a portmanteau term, and it relates to bookmarks and applets. It is obvious.

Initial term was coined by the other guy on the site: https://web.archive.org/web/20000815062830/http://www.bookmarklets.com/about/

The initial definition is:
"bookmarklet is a tiny program (a JavaScript application) contained in a bookmark (the URL is a "javascript:" URL) which can be saved and used the same way you use normal bookmarks."

So, please. Bookmarklets refere to bookmarks. And they run client-side script.

My `F2` hotkey of Tridactyl does not use any bookmarks, it launches a script inside a browser. That is why section is renamed `Bookmarklets -> Browser-side script` - because it is a proper name for the section that talks about setting-up client-side browser script.

**Comment by Anton-Latukha** [comment]
It very strange that a person needs to go to such length to restore all the facts to prove something that reasonable and obvious and such a minor detail in the work.

**Comment by alphapapa** [comment]
@Anton-Latukha If you are dissatisfied with how I run this project, you are free to fork it and maintain your own version.

**Comment by Anton-Latukha** [comment]
Yes, I am able, but that would be immoral and multiply the efforts if we would rival instead of working together. People should only fork when they encouraged to transfer the project or of real necessity of management.

I've send not a personal argument, but to the process, somehow people try to hold human texts to the standards of the prodremming code review, and to the scientific peer review - and that is not a way to manage the documentation, it is not a programming code, it is a human language that is always debatable and has an infinite number of possible options of writing it. Programmin code is a direct implementation of some algorithm, text is not - why people hold them to the same standard, while the nature and use of them completely differ.

Look at how much arguing happens about a patch of text. 1.5 years passed by, and text and instruction improvements for people still not got in, and maintainer started to threaten me. For what, that contributor submitted a text and instructions that were not there before?

**Comment by Anton-Latukha** [comment]
If you no longer use the project and want to transfer it - put a banner in README and find a trustable person to transfer the project to.

I have basic Elisp knowledge comparing to you, I may maintain the project, I would accept text edits more openly, and learn on my mistakes with Elisp, and longterm I would collaborate with the extension project then, since the projects have same agenda and their main code is the same, it is smart to merge them or split the efforts by modularization.

**Comment by alphapapa** [comment]
> maintainer does emotional response threatening him.

I did nothing of the kind.  It is you who is out-of-line here.

Differences of opinion are common in FOSS.  Forking is a time-honored tradition, and it is preferable to long-winded arguments over the etymology of jargon.

It is clear that our development philosophies are not aligned, so please honor that tradition rather than continuing to browbeat me.

**Comment by Anton-Latukha** [comment]
Very strange conversation.

As I said, you've could just changed yourself the wording however you want. It is strange to force contributor to write human text only as you want it.

The model for human text that I preset is more open than widely used "treating human text submission as code review". I submitted the simple text changes, you is one who started arguing about my word use, and I put proofs behind my word use - that is all that is happened here. Please, understand that you started the debate in the first place, I only addressed the facts.

**Comment by alphapapa** [comment]
I tried being reasonable.  Please don't comment on this issue again.

**Comment by notevenaperson** [comment]
@Anton-Latukha Thanks for the :bind snippet

**Pull request closed without merging**
