### PR TITLE
fix python2, remove {begin,end}_html and fix occasional package install breakage

### PR DESCRIPTION
**Pull request by fishman**

### CODE REVIEW

**Comment by alphapapa** [comment]
Hi,

Thanks for submitting this PR.  

The package headers I will wait on, until I decide to submit this to MELPA, at which point several things will need to be done.

The function you copied from the related issue should probably be added, but what really needs to be done is to convert this package to use the related code from `org-web-tools` (which is basically factored out of this package).  I guess we might as well add the function until I do that, though, but I'd like to do that separately from these other changes.

About the Python change, is that really necessary?  What platform are you using?  Python 2 is the default on my systems.  Does that code not work under Python 3?  I guess using `python2` as the executable is probably a pretty safe thing to do at this point, but I don't know how universal that is across platforms.  So:

1.  Is there a way to adjust the code to work under both Python 2 and Python 3?
2.  If not, it would probably be best to use a variable to set the executable name.  Or, maybe there is a way to determine the Python 2 executable from some existing Emacs code, to avoid the user having to configure it.

Let me know what you think.  Thanks.

**Comment by fishman** [comment]
I actually noticed your org-web-tools. And I noticed that it's much nicer and more modular. Originally I tried to import just use your org-web-tools directly to build a org-protocol handler but to be honest i'm not entirely sure how since I i never properly learned at CL.

I'm in archlinux . The python3 version is as follows:

    python -c "import sys, urllib.parse; print(urllib.parse.quote(sys.stdin.read()[:-1], safe=''))"             

Anyway, the actual begin_html end_html I added seems to not work properly. so it's my bad

**Comment by alphapapa** [comment]
> I actually noticed your org-web-tools. And I noticed that it's much nicer and more modular. Originally I tried to import just use your org-web-tools directly to build a org-protocol handler but to be honest i'm not entirely sure how since I never learned at CL.

org-protocol can be confusing to work with.

> I'm in archlinux . The python3 version is as follows:

The best way to handle this would be to write one version that works in both Python 2 and 3, that way it wouldn't depend on the executable name and wouldn't require Python 3.

> Anyway, the actual begin_html end_html I added seems to not work properly. so it's my bad

I don't see why it wouldn't work, but I haven't tested it myself.

**Comment by alphapapa** [comment]
@fishman Please see the recent PR #31 which should fix the Python issues.

If the other issues are still relevant, let's discuss them separately.  Let me know if they are, and I'll open issues for them.  Thanks for submitting this PR.

**Pull request closed without merging**
